### ISSUE TITLE
Typo in [Remodeling an Ember App] post

### ISSUE THREAD

**Issue by noahsb** [jenweber/empress-blog-jenweber#8]
### Subject of the issue

Typo in `Remodeling an Ember App - Codemods and jQuery` blog post

### Steps to reproduce

Navigate to https://www.jenweber.dev/remodeling-an-ember-app---codemods
Read the first sentence:

> "When you need to upgrade and ember app..."

### Expected behaviour

Sentence should read:
> "When you need to upgrade an ember app..."

### Actual behaviour

Sentence instead reads (notice the *and* vs *an*):
> "When you need to upgrade and ember app..."

Would be happy to submit a simple PR to fix this :) thanks for the great post!

**Comment by jenweber** [comment]
Fixed, thank you!
